[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
paq1-lib-error-handler = { git = "https://github.com/paq1/paq1-lib-error-handler.git", branch = "master", features = ["combine"] }
async-trait = { version = "0.1.80" }